//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Reflection;
    using System.Data.Entity.ModelConfiguration;

    public partial class VehicleDbEntities : DbContext
    {
        public VehicleDbEntities()
            : base("name=VehicleDbEntities")
        {
            //Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }
       
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
           

            throw new UnintentionalCodeFirstException();
        }


        public virtual DbSet<VehicleMake> VehicleMakes { get; set; }
        public virtual DbSet<VehicleModel> VehicleModels { get; set; }

    }
}
